# Database configuration

postgres:
  user: postgres     
  password: "G/civs5s6XtWyLi0IfOILSPq"   
  database: product_service_database
  name: product-service-database

# Products Service configuration

products:
  service:
   image: "carlosalves77/products-service:v.1.0.0"
appName: products-service





