apiVersion: v1
kind: Service
metadata:
  name: product-service-database
  namespace: default
spec:
  selector:
    app: product-service-database
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None